#disable the blank line at the start of the prompt
add_newline = true

[line_break]
disabled = true


[container]
format = '[$symbol \[$name\]]($style) '

[directory]
read_only = 'ğŸ”’'

[docker_context]
format = 'via [ğŸ‹ $context](blue bold)'
symbol = 'R '
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
disabled = false

[git_branch]
symbol = 'ğŸŒ± '
truncation_length = 4
truncation_symbol = ''
#always_show_remote = true
style = 'bold purple'


#[hostname]
#ssh_only = false
#format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
#trim_at = '.companyname.com'
#disabled = false


#[memory_usage]
#disabled = false
#threshold = -1
#symbol = ' '
#style = 'bold dimmed green'


[java]
symbol ='â˜• '
version_format = 'v${raw}'

#[localip]
#ssh_only = false
#format = '@[$localipv4](bold red) '
#disabled = false

[lua]
symbol = 'ğŸŒ™ '


[package]
format = 'via [ğŸ $version](208 bold) '
symbol = 'ğŸ“¦ '


[php]
symbol = 'ğŸ˜ '
detect_extensions=['php']

[rust]
symbol= 'ğŸ¦€ '	

